trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
    dockerComposePath: /tmp/docker-compose

steps:
  - script: |
      curl https://cdn.azul.com/zulu/bin/zulu14.27.1-ca-jdk14-linux_x64.tar.gz --output $(Agent.TempDirectory)/jdk-latest-linux_x64.tar.gz
  - bash: |
     sudo mkdir $(dockerComposePath)
     sudo curl -SL https://github.com/docker/compose/releases/download/1.29.2/docker-compose-linux-x86_64 -o $(dockerComposePath)/docker-compose
     sudo chmod 755 $(dockerComposePath)
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: "14"
      jdkArchitectureOption: x64
      jdkSourceOption: LocalDirectory
      jdkFile: $(Agent.TempDirectory)/jdk-latest-linux_x64.tar.gz
      jdkDestinationDirectory: $(Agent.ToolsDirectory)/binaries/openjdk
      cleanDestinationDirectory: true
  - task: Gradle@2
    condition: succeeded()
    inputs:
      gradleWrapperFile: 'gradlew'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.14'
      jdkArchitectureOption: 'x64'
      tasks: 'test'
  - script: |
      ./build.sh
    displayName: 'Build project artifacts'
  - task: CopyFiles@2
    inputs:
      Contents: 'kube-config-*.yml'
      TargetFolder: '$(build.artifactstagingdirectory)'
    displayName: 'Copy Kube Config Files'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'manifest'
      publishLocation: 'Container'
    displayName: 'Publish Kube Config'
  - task: DockerCompose@1
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'ITADEV2-MSDataServicesAzure'
      azureContainerRegistry: '{"loginServer":"itadevacr.azurecr.io", "id" : "/subscriptions/675d7977-79af-4b94-b0bd-26d4095a4ffb/resourceGroups/ITA-MSDataServices-Dev-East1/providers/Microsoft.ContainerRegistry/registries/itadevacr"}'
      dockerComposeFile: '**/docker-compose.yml'
      action: 'Build services'
      additionalImageTags: '$(Build.BuildId)'
    displayName: 'Build Docker image'
  - task: DockerCompose@1
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'ITADEV2-MSDataServicesAzure'
      azureContainerRegistry: '{"loginServer":"itadevacr.azurecr.io", "id" : "/subscriptions/675d7977-79af-4b94-b0bd-26d4095a4ffb/resourceGroups/ITA-MSDataServices-Dev-East1/providers/Microsoft.ContainerRegistry/registries/itadevacr"}'
      dockerComposeFile: '**/docker-compose.yml'
      action: 'Push services'
      additionalImageTags: '$(Build.BuildId)'
    displayName: 'Push Docker image'