trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  imageName: 'vangoscontainerregistry.azurecr.io/ita-dataloader'
  containerRegestry: 'vangoscontainerregistry.azurecr.io'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: Install Node
- script: |
    ./build.sh
  displayName: Build project artifacts
- task: Docker@2
  displayName: Build docker image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: docker/Dockerfile
#- task: Docker@2
#  displayName: Push docker image
#  inputs:
#    containerRegistry: $(containerRegestry)
#    repository: $(imageName)
#    command: push
#    tags: latest
