trigger:
  - master

pool:
  vmImage: 'ubuntu-16.04'

steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'test'
  - script: |
      ./build.sh
    displayName: 'Build project artifacts'
  - task: CopyFiles@2
    inputs:
      Contents: 'kube-config-prod.yml'
      TargetFolder: '$(build.artifactstagingdirectory)'
    displayName: 'Copy Kube Config'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'manifest'
      publishLocation: 'Container'
    displayName: 'Publish Kube Config'
  - task: DockerCompose@0
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'ITAPROD-MSDataServicesAzure'
      azureContainerRegistry: '{"loginServer":"itadrupalprodeast1.azurecr.io", "id" : "/subscriptions/f77f3fb8-7095-4b35-aec0-49340169db57/resourceGroups/ITA-Drupal-Prod-East1/providers/Microsoft.ContainerRegistry/registries/itadrupalprodeast1"}'
      dockerComposeFile: '**/docker-compose-prod.yml'
      action: 'Build services'
      additionalImageTags: '$(Build.BuildId)'
    displayName: 'Build Docker image'
  - task: DockerCompose@0
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'ITAPROD-MSDataServicesAzure'
      azureContainerRegistry: '{"loginServer":"itadrupalprodeast1.azurecr.io", "id" : "/subscriptions/f77f3fb8-7095-4b35-aec0-49340169db57/resourceGroups/ITA-Drupal-Prod-East1/providers/Microsoft.ContainerRegistry/registries/itadrupalprodeast1"}'
      dockerComposeFile: '**/docker-compose-prod.yml'
      action: 'Push services'
      additionalImageTags: '$(Build.BuildId)'
    displayName: 'Push Docker image'
