trigger:
  - master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  containerRegestryServiceConnection: 'ITADEV2-MSDataServicesAzure'
  imageName: 'dataservices.azurecr.io/ita-dataloader'

steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build test'
  - script: |
      ./build.sh
    displayName: Build project artifacts
  - task: Docker@2
    displayName: Build & Push docker image
    inputs:
      containerRegistry: $(containerRegestryServiceConnection)
      repository: $(imageName)
      command: 'buildAndPush'
      Dockerfile: 'docker/Dockerfile'
      tags: 'latest'
