trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      curl https://cdn.azul.com/zulu/bin/zulu14.27.1-ca-jdk14-linux_x64.tar.gz --output $(Agent.TempDirectory)/jdk-latest-linux_x64.tar.gz
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: "14"
      jdkArchitectureOption: x64
      jdkSourceOption: LocalDirectory
      jdkFile: $(Agent.TempDirectory)/jdk-latest-linux_x64.tar.gz
      jdkDestinationDirectory: $(Agent.ToolsDirectory)/binaries/openjdk
      cleanDestinationDirectory: true
  - task: Gradle@2
    condition: succeeded()
    inputs:
      gradleWrapperFile: 'gradlew'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.14'
      jdkArchitectureOption: 'x64'
      tasks: 'test'
  - script: |
      ./build.sh
    displayName: 'Build project artifacts'
  - task: CopyFiles@2
    inputs:
      Contents: 'kube-config-prod.yml'
      TargetFolder: '$(build.artifactstagingdirectory)'
    displayName: 'Copy Kube Config'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'manifest'
      publishLocation: 'Container'
    displayName: 'Publish Kube Config'
  - task: DockerCompose@0
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'ITAPROD-MSDataServicesAzure'
      azureContainerRegistry: '{"loginServer":"itadrupalprodeast1.azurecr.io", "id" : "/subscriptions/f77f3fb8-7095-4b35-aec0-49340169db57/resourceGroups/ITA-Drupal-Prod-East1/providers/Microsoft.ContainerRegistry/registries/itadrupalprodeast1"}'
      dockerComposeFile: '**/docker-compose-prod.yml'
      action: 'Build services'
      additionalImageTags: '$(Build.BuildId)'
    displayName: 'Build Docker image'
  - task: DockerCompose@0
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'ITAPROD-MSDataServicesAzure'
      azureContainerRegistry: '{"loginServer":"itadrupalprodeast1.azurecr.io", "id" : "/subscriptions/f77f3fb8-7095-4b35-aec0-49340169db57/resourceGroups/ITA-Drupal-Prod-East1/providers/Microsoft.ContainerRegistry/registries/itadrupalprodeast1"}'
      dockerComposeFile: '**/docker-compose-prod.yml'
      action: 'Push services'
      additionalImageTags: '$(Build.BuildId)'
    displayName: 'Push Docker image'
