kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: ita-dataloader
  namespace: mdsnamespace
  labels:
    app: ita-dataloader
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: ita-dataloader
    spec:
      containers:
      - name: ita-dataloader
        image: dataservices.azurecr.io/ita-dataloader:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: AZURE_STORAGE_ACCOUNT
            value: <azure-storage-account>
          - name: AZURE_STORAGE_ACCOUNT_KEY
            value: <azure-storage-account-key>
          - name: FLYWAY_URL
            value: <azure-sql-database-url>
          - name: FLYWAY_USER
            value: <azure-sql-database-username>
          - name: FLYWAY_PASSWORD
            value: <azure-sql-database-password>
          - name: AZURE_OAUTH_CLIENT_ID
            value: <azure-oauth-client-id>
          - name: AZURE_OAUTH_CLIENT_SECRET
            value: <azure-oauth-client-secret>
          - name: AZURE_OAUTH_TENANT_ID
            value: <azure-oauth-tenant-id>
          - name: DATAFACTORY_CLIENT_ID
            value: <azure-datafactory-client-id>
          - name: DATAFACTORY_CLIENT_SECRET
            value: <azure-datafactory-client-secret>
          - name: DATAFACTORY_NAME
            value: <azure-datafactory-name>
          - name: DATAFACTORY_RESOURCE_GROUP
            value: <azure-datafactory-resource-group>
          - name: AZURE_SUBSCRIPTION_ID
            value: <azure-datafactory-tenant-id>
          - name: AZURE_TENANT_ID
            value: <azure-datafactory-tenant-id>

      restartPolicy: Always
---

kind: Service
apiVersion: v1
metadata:
  name: ita-dataloader
  namespace: mdsnamespace
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
  selector:
    app: ita-dataloader
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ita-dataloader
  namespace: mdsnamespace
spec:
  rules:
    - host: <url>
      http:
        paths:
          - path: /
            backend:
              serviceName: ita-dataloader
              servicePort: 80
  tls:
    - hosts:
        - <url>
      secretName: tls-secret
