kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: ita-dataloader
  namespace: mdsnamespace
  labels:
    app: ita-dataloader
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: ita-dataloader
    spec:
      containers:
      - name: ita-dataloader
        image: itadevacr.azurecr.io/ita-dataloader:#{Release.Artifacts._InternationalTradeAdministration.ita-dataloader.BuildId}#
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: AZURE_STORAGE_ACCOUNT
            value: #{AZURE_STORAGE_ACCOUNT}#
          - name: AZURE_STORAGE_ACCOUNT_KEY
            value: #{AZURE_STORAGE_ACCOUNT_KEY}#
          - name: FLYWAY_URL
            value: #{FLYWAY_URL}#
          - name: FLYWAY_USER
            value: #{FLYWAY_USER}#
          - name: FLYWAY_PASSWORD
            value: #{FLYWAY_PASSWORD}#
          - name: AZURE_OAUTH_CLIENT_ID
            value: #{AZURE_OAUTH_CLIENT_ID}#
          - name: AZURE_OAUTH_CLIENT_SECRET
            value: #{AZURE_OAUTH_CLIENT_SECRET}#
          - name: AZURE_OAUTH_TENANT_ID
            value: #{AZURE_OAUTH_TENANT_ID}#
          - name: DATAFACTORY_CLIENT_ID
            value: #{DATAFACTORY_CLIENT_ID}#
          - name: DATAFACTORY_CLIENT_SECRET
            value: #{DATAFACTORY_CLIENT_SECRET}#
          - name: DATAFACTORY_NAME
            value: #{DATAFACTORY_NAME}#
          - name: DATAFACTORY_RESOURCE_GROUP
            value: #{DATAFACTORY_RESOURCE_GROUP}#
          - name: AZURE_SUBSCRIPTION_ID
            value: #{AZURE_SUBSCRIPTION_ID}#
          - name: AZURE_TENANT_ID
            value: #{AZURE_TENANT_ID}#
          - name: SPRING_PROFILES_ACTIVE
            value: production
          - name: BUILD_ID
            value: #{Release.Artifacts._InternationalTradeAdministration.ita-dataloader.BuildId}#
      restartPolicy: Always
---

kind: Service
apiVersion: v1
metadata:
  name: ita-dataloader
  namespace: mdsnamespace
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
  selector:
    app: ita-dataloader
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ita-dataloader
  namespace: mdsnamespace
spec:
  rules:
    - host: dataloader-itadev2.vangos-cloudapp.us
      http:
        paths:
          - path: /
            backend:
              serviceName: ita-dataloader
              servicePort: 80
  tls:
    - hosts:
        - dataloader-itadev2.vangos-cloudapp.us
      secretName: tls-secret
