spring:
  profiles: development
  servlet:
    multipart:
      max-file-size: 250MB
      max-request-size: 250MB
build-id: n/a
---
spring:
  profiles: staging
  jpa:
    show-sql: false
    format_sql: true
  servlet:
    multipart:
      max-file-size: 250MB
      max-request-size: 250MB
storage-params:
  azure-storage-account: ${AZURE_STORAGE_ACCOUNT}
  azure-storage-account-key: ${AZURE_STORAGE_ACCOUNT_KEY}
datafactory:
  client-id: ${DATAFACTORY_CLIENT_ID}
  client-secret: ${DATAFACTORY_CLIENT_SECRET}
  name: ${DATAFACTORY_NAME}
  resource-group: ${DATAFACTORY_RESOURCE_GROUP}
azure-tenant-id: ${AZURE_TENANT_ID}
azure-subscription-id: ${AZURE_SUBSCRIPTION_ID}
build-id: n/a

---
spring:
  profiles: production
  servlet:
    multipart:
      max-file-size: 250MB
      max-request-size: 250MB
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${AZURE_OAUTH_CLIENT_ID}
            client-secret: ${AZURE_OAUTH_CLIENT_SECRET}
azure:
  activedirectory:
    tenant-id: ${AZURE_OAUTH_TENANT_ID}
    active-directory-groups: TSI_AllUsers
storage-params:
  azure-storage-account: ${AZURE_STORAGE_ACCOUNT}
  azure-storage-account-key: ${AZURE_STORAGE_ACCOUNT_KEY}
datafactory:
  client-id: ${DATAFACTORY_CLIENT_ID}
  client-secret: ${DATAFACTORY_CLIENT_SECRET}
  name: ${DATAFACTORY_NAME}
  resource-group: ${DATAFACTORY_RESOURCE_GROUP}
azure-tenant-id: ${AZURE_TENANT_ID}
azure-subscription-id: ${AZURE_SUBSCRIPTION_ID}
build-id: ${BUILD_ID}
