spring:
  profiles:
    active: development
  h2:
    console:
      enabled: true
      path: /h2-console
      mode: MySQL
  datasource:
    url: jdbc:h2:mem:terrafreights;MODE=MySQL
    username: SA
    password:
---
spring:
  profiles:
    active: staging
  jpa:
    show-sql: true
    format_sql: true
  datasource:
    url: ${AZURE_DB_URL}
    username: ${AZURE_DB_USERNAME}
    password: ${AZURE_DB_PASSWORD}
storage-params:
  azure-storage-account: ${AZURE_STORAGE_ACCOUNT}
  azure-storage-account-key: ${AZURE_STORAGE_ACCOUNT_KEY}
---
spring:
  profiles: production
  jpa:
    show-sql: false
    format_sql: true
  datasource:
    url: ${AZURE_DB_URL}
    username: ${AZURE_DB_USERNAME}
    password: ${AZURE_DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${AZURE_OAUTH_CLIENT_ID}
            client-secret: ${AZURE_OAUTH_CLIENT_SECRET}
azure:
  activedirectory:
    tenant-id: ${AZURE_OAUTH_TENANT_ID}
    active-directory-groups: EDSP
storage-params:
  azure-storage-account: ${AZURE_STORAGE_ACCOUNT}
  azure-storage-account-key: ${AZURE_STORAGE_ACCOUNT_KEY}
